### ISSUE TITLE
Plugin depending on plugin will not load correctly

### ISSUE THREAD

**Issue by tomvlk** [eXpansionPluginPack/eXpansion#220]
Hey :),
When I depend a plugin on another plugin it's sometimes not loading at all, the logs says 'retry' but it doesn't retry loading it again. It's kinda random, sometimes it is and sometimes it's giving me issues.
It's on PHP 7 (just a note).

Which way do you need to make the dependency, basically the plugins are using eachother, and I'm defining the dependency in the child plugin. Maybe could be someting with this?

**Comment by oliverde8** [comment]
Confirmed, 

The method displays Retry because it is used during the start script, and at that instances it does retry automatically. 

Need to make it retry properly :smile:

**Comment by tomvlk** [comment]
What you can do is make a sort of dependency tree with node to node dependencies, then calculate the order to start. 
Something like this: https://github.com/JosephMoniz/php-dependency-graph#examples

**Comment by oliverde8** [comment]
The issue, is the plugin dependency is handled on the plugin it self, and not in the MetaData. 
I get all the metadata for all plugins started or not, but for compatibility I don't have it. I need first to "try" and load the plugin (which will create the object with the information) and I get it at the moment. 

That's due to the way it was put together in Manialive. On long term we will surely move it all to MetaData, I already have a few idea how to do it without rewriting everything on Manialive side.

For now I will do a fix :) 

and created an issue not to forget about it #222

**Comment by oliverde8** [comment]
The fix is here 😄
